definitions:
  models.ImageInputData:
    properties:
      architecture:
        type: string
      basePkg:
        items:
          $ref: '#/definitions/models.pkgData'
        type: array
      customPkg:
        items:
          $ref: '#/definitions/models.pkgData'
        type: array
      eulerVersion:
        type: string
      id:
        type: integer
      outFormat:
        type: string
    type: object
  models.pkgData:
    properties:
      pkgMd5:
        type: string
      pkgName:
        type: string
    type: object
info:
  contact: {}
paths:
  /images/delete/:id:
    delete:
      consumes:
      - application/json
      description: update single data
      parameters:
      - description: The key for staticblock
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: delete
      tags:
      - meta Manager
  /images/get/{id}:
    get:
      consumes:
      - application/json
      description: get single one
      parameters:
      - description: The key for staticblock
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: get
      tags:
      - meta Manager
  /images/insert:
    post:
      consumes:
      - application/json
      description: insert single data
      parameters:
      - description: body for Metadata content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ImageInputData'
      produces:
      - application/json
      responses: {}
      summary: create
      tags:
      - meta Manager
  /images/param/getBaseData/:
    get:
      consumes:
      - application/json
      description: get architecture, release Version, output Format ,and default package
        name list
      produces:
      - application/json
      responses: {}
      summary: GetBaseData param
      tags:
      - meta Manager
  /images/param/getCustomePkgList/:
    get:
      consumes:
      - application/json
      description: get default package name list. this list load from https://raw.githubusercontent.com/omnibuildplatform/omni-imager/main/etc/openEuler-minimal.json
      produces:
      - application/json
      responses: {}
      summary: GetCustomePkgList param
      tags:
      - meta Manager
  /images/query:
    get:
      consumes:
      - application/json
      description: use param to query multi datas
      parameters:
      - description: project name
        in: query
        name: project_name
        required: true
        type: string
      - description: package name
        in: query
        name: pkg_name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: query multi datas
      tags:
      - meta Manager
  /images/update:
    put:
      consumes:
      - application/json
      description: update single data
      parameters:
      - description: body for Metadata content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ImageInputData'
      produces:
      - application/json
      responses: {}
      summary: update
      tags:
      - meta Manager
swagger: "2.0"
